# replace
* replace(to_replace=비교값, value=치환값)
* NaN값은 np.nan으로 비교가능

# 데이터 셋 로드

In [154]:
import pandas as pd

In [155]:
df=pd.read_csv('data/nan_test.csv')

In [156]:
import numpy as np

In [157]:
df.replace(to_replace=np.nan, value="치환값")

n1  n2  n3 nan_1 nan_2
0   0   1   2   1.7   치환값
1   3   4   2   치환값   치환값
2   3   4   8   2.4   치환값
3   9  10  11   치환값   치환값
4  12  10  14   1.2   치환값
5  15  16  17   치환값   1.0

In [158]:
#특정 열만 변경
df.replace({'nan_2':np.nan}, value="변경", inplace=True)
#df
df.replace({'nan_1':np.nan}, {"nan_1":"변경하자"}, inplace=True)
df

n1  n2  n3 nan_1 nan_2
0   0   1   2   1.7    변경
1   3   4   2  변경하자    변경
2   3   4   8   2.4    변경
3   9  10  11  변경하자    변경
4  12  10  14   1.2    변경
5  15  16  17  변경하자   1.0

### 특정 데이터 비교

In [159]:
df = pd.read_csv('data/bicycle.csv')
df.head()

자전거번호              대여일시  대여소번호               대여소명  대여거치대  \
0  SPB-23220   2019-11-01 8:48    646  장한평역 1번출구 (국민은행앞)    3.0   
1  SPB-16216   2019-11-04 8:38    646  장한평역 1번출구 (국민은행앞)    2.0   
2  SPB-21097   2019-11-04 8:46    646  장한평역 1번출구 (국민은행앞)    1.0   
3  SPB-22292   2019-11-05 8:34    646  장한평역 1번출구 (국민은행앞)    1.0   
4  SPB-07935  2019-11-05 12:29    512        뚝섬역 1번 출구 옆   11.0   

               반납일시  반납대여소번호 반납대여소명  반납거치대  이용시간    이용거리   나이  
0   2019-11-01 9:01        3   중랑센터    7.0  12.0  1100.0   50  
1   2019-11-04 8:56        3   중랑센터    2.0   7.0  1420.0   31  
2   2019-11-04 8:57        3   중랑센터    7.0  10.0     NaN   32  
3   2019-11-05 8:45        3   중랑센터    NaN  10.0  1380.0   21  
4  2019-11-05 12:39        3   중랑센터    7.0  10.0  1650.0  120

In [160]:
df.loc[ df['대여소번호']==646].head()


자전거번호             대여일시  대여소번호               대여소명  대여거치대  \
0  SPB-23220  2019-11-01 8:48    646  장한평역 1번출구 (국민은행앞)    3.0   
1  SPB-16216  2019-11-04 8:38    646  장한평역 1번출구 (국민은행앞)    2.0   
2  SPB-21097  2019-11-04 8:46    646  장한평역 1번출구 (국민은행앞)    1.0   
3  SPB-22292  2019-11-05 8:34    646  장한평역 1번출구 (국민은행앞)    1.0   
5  SPB-18401  2019-11-06 8:52    646  장한평역 1번출구 (국민은행앞)    1.0   

              반납일시  반납대여소번호 반납대여소명  반납거치대  이용시간    이용거리  나이  
0  2019-11-01 9:01        3   중랑센터    7.0  12.0  1100.0  50  
1  2019-11-04 8:56        3   중랑센터    2.0   7.0  1420.0  31  
2  2019-11-04 8:57        3   중랑센터    7.0  10.0     NaN  32  
3  2019-11-05 8:45        3   중랑센터    NaN  10.0  1380.0  21  
5  2019-11-06 9:09        3   중랑센터    7.0  11.0  1350.0  30

In [161]:
df.loc[ df['대여소번호']==646 , ['대여거치대','반납일시']]
#df[ df['대여소번호'] ==646][['대여거치대','반납일시']]

대여거치대              반납일시
0     3.0   2019-11-01 9:01
1     2.0   2019-11-04 8:56
2     1.0   2019-11-04 8:57
3     1.0   2019-11-05 8:45
5     1.0   2019-11-06 9:09
6     1.0   2019-11-06 9:10
8     2.0   2019-11-11 8:42
9     8.0  2019-11-11 10:17
10    8.0   2019-11-12 8:44
11    9.0   2019-11-13 8:38
12    4.0   2019-11-13 9:08
13    NaN  2019-11-14 10:01
14   10.0  2019-11-14 10:02
15    1.0   2019-11-15 8:50
16    6.0   2019-11-18 8:39
17    4.0   2019-11-18 9:01
18    NaN   2019-11-21 8:44
19    2.0   2019-11-21 9:04
21    5.0   2019-11-25 8:49
22    6.0   2019-11-26 8:48
24    6.0   2019-11-28 8:44

In [162]:
# df[df['대여소번호']==646]['이용거리'].fillna(789.789)
df.loc[ df['대여소번호']==646, '이용거리' ].fillna(123.45678)

0     1100.00000
1     1420.00000
2      123.45678
3     1380.00000
5     1350.00000
6     1390.00000
8     1160.00000
9     1060.00000
10    1300.00000
11    1060.00000
12     123.45678
13    1140.00000
14    1220.00000
15    1370.00000
16    1350.00000
17    1350.00000
18    1130.00000
19    1330.00000
21    1310.00000
22    1380.00000
24    1070.00000
Name: 이용거리, dtype: float64

In [163]:
df.loc[ df['대여소번호']==646, '이용거리' ].fillna(123.45678)

0     1100.00000
1     1420.00000
2      123.45678
3     1380.00000
5     1350.00000
6     1390.00000
8     1160.00000
9     1060.00000
10    1300.00000
11    1060.00000
12     123.45678
13    1140.00000
14    1220.00000
15    1370.00000
16    1350.00000
17    1350.00000
18    1130.00000
19    1330.00000
21    1310.00000
22    1380.00000
24    1070.00000
Name: 이용거리, dtype: float64

In [164]:
df.loc[df['대여소번호']==646, '이용거리'] = df.loc[ df['대여소번호']==646, '이용거리' ].fillna(123.45678)

In [165]:
df.loc[df['대여소번호']==646, '이용거리']

0     1100.00000
1     1420.00000
2      123.45678
3     1380.00000
5     1350.00000
6     1390.00000
8     1160.00000
9     1060.00000
10    1300.00000
11    1060.00000
12     123.45678
13    1140.00000
14    1220.00000
15    1370.00000
16    1350.00000
17    1350.00000
18    1130.00000
19    1330.00000
21    1310.00000
22    1380.00000
24    1070.00000
Name: 이용거리, dtype: float64

In [166]:
df.loc[df['대여소번호']==646,'이용거리']= df[df['대여소번호']==646]['이용거리'].fillna(789.789)

In [167]:
df[df['대여소번호']==646]['이용거리']

0     1100.00000
1     1420.00000
2      123.45678
3     1380.00000
5     1350.00000
6     1390.00000
8     1160.00000
9     1060.00000
10    1300.00000
11    1060.00000
12     123.45678
13    1140.00000
14    1220.00000
15    1370.00000
16    1350.00000
17    1350.00000
18    1130.00000
19    1330.00000
21    1310.00000
22    1380.00000
24    1070.00000
Name: 이용거리, dtype: float64

# Quiz-1
* 결측치를 해결하시오
    #### 결측치 제거(행 삭제)
    #### 결측치 치환
        * Gender : Male
        * Married : Yes
        * Dependents : NaN 최빈값으로 변경. '3+'는 3으로 변경
        * Self_Employed : 이전값
        * LoanAmount : 이후값
        * Loan_Amount_Term : 평균값
        * Credit_History : 1.0

In [168]:
df = pd.read_csv('data/loan-train.csv')

In [169]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [170]:
#데이터셋 행,열 개수 출력 및 결측치 확인
print(df.shape)
df.isnull().sum()

(614, 13)


Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [171]:
#결측치 제거 후 확인

print(df.dropna( axis=0 ))


      Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0           

In [172]:
#데이터셋 다시 로드 후 진행
df = pd.read_csv('data/loan-train.csv')

In [173]:
# 데이터셋 행, 열 확인 및 결측값 확인
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [174]:
#Gender 유니크값 확인
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [175]:
# Gender NaN Male 값으로 치환 후 확인
# df['Gender'].replace(to_replace=np.nan, value="Male")
df.replace({'Gender':np.nan}, value="Male" , inplace=True)
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [176]:
# Married 치환 전 유니크값 확인
df['Married'].unique()

array(['No', 'Yes', nan], dtype=object)

In [177]:
# Married : Yes 치환 후 결과 확인
df.replace({'Married':np.nan}, value="Yes", inplace=True)
df['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [178]:
# Dependents 변경 전 확인
df['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [179]:
# Dependents NaN값 최빈값으로 변경 후 확인
df.replace({'Dependents': np.nan}, value= df['Dependents'].mode()[0], inplace=True)
df['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [180]:
# Dependents 3+ -> 3으로 변경 후 확인
df.replace({'Dependents': '3+'}, value= "3", inplace=True)
df['Dependents'].unique()


array(['0', '1', '2', '3'], dtype=object)

In [181]:
# Self_Employed 변경전 확인
df['Self_Employed'].unique()

array(['No', 'Yes', nan], dtype=object)

In [183]:
# Self_Employed 이전 값으로 변경 후 확인
df['Self_Employed'].fillna(method='pad', inplace=True)
df['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
# LoanAmount 변경전 확인
df['LoanAmount'].unique()

In [184]:
# LoanAmount 이후(다음) 값으로 변경 후 확인
df['LoanAmount'].fillna(method='bfill', inplace=True)
df['LoanAmount'].unique()

array([128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70., 109.,
       200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315., 116.,
       112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320., 144.,
       184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97., 135.,
       180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187., 113.,
       176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,  25.,
       137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,  85.,
       259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242., 129.,
        30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87., 101.,
       495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,  90.,
       166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,  42.,
       280., 140., 155., 123., 279., 192., 304., 330., 150., 207., 436.,
        78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300., 376.,
       117.,  71., 490., 173.,  46., 228., 308., 23

In [185]:
# Loan_Amount_Term 변경전 확인
df['Loan_Amount_Term'].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [188]:
# Loan_Amount_Term 평균 값으로 변경 후 확인
df['Loan_Amount_Term'].fillna( df['Loan_Amount_Term'].mean() , inplace =True)
df['Loan_Amount_Term'].unique()

array([360., 120., 240., 342., 180.,  60., 300., 480.,  36.,  84.,  12.])

In [191]:
# Credit_History 변경전 확인
# Credit_History 1.0  변경 후 확인
df['Credit_History'].unique()
df['Credit_History'].fillna(1.0, inplace=True)
df['Credit_History'].unique()

array([1., 0.])

In [193]:
# 최종 결과 확인
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64