In [1]:
import pandas as pd
df = pd.read_csv('data/IRIS.csv')
df.head().T

0            1            2            3            4
sepal_length          5.1          4.9          4.7          4.6          5.0
sepal_width           3.5          3.0          3.2          3.1          3.6
petal_length          1.4          1.4          1.3          1.5          1.4
petal_width           0.2          0.2          0.2          0.2          0.2
species       Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

In [2]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [3]:
species_num = {'Iris-setosa': 0 , 'Iris-versicolor':1 , 'Iris-virginica' : 2}

In [4]:
df['species_num'] = df['species'].map(species_num)

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'species_num'],
      dtype='object')

In [6]:
features = ['sepal_length', 
            'sepal_width', 'petal_length', 'petal_width' ]
label = 'species_num'
X, y = df[features], df[label]

In [7]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
X_min_max = min_max_scaler.fit_transform(X)
X_min_max

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =\
                train_test_split(X_min_max,y,test_size=0.2)

In [9]:
X_train.shape

(120, 4)

In [10]:
int(X_train.shape[0]*0.2)

24

In [12]:
percent = int(X_train.shape[0]*0.2)

#검증데이터
validate_X_train = X_train[ :percent]
validate_y_train = y_train[ :percent]

#학습데이터
learn_X_train = X_train[percent : ]
learn_y_train = y_train[percent : ]




In [13]:
print('전체 데이터 수 : ', X_train.shape)
print('검증 데이터 수 : ', validate_X_train.shape)
print('학습 데이터 수 : ', learn_X_train.shape)

전체 데이터 수 :  (120, 4)
검증 데이터 수 :  (24, 4)
학습 데이터 수 :  (96, 4)


### 모델 생성 및 설정

In [14]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add( Dense(64, activation='relu', input_dim=4))
model.add( Dense(32, activation='relu'))
model.add( Dense(3, activation='softmax'))

### loss 학습 설정

In [15]:
model.compile( optimizer = 'adam' ,metrics='acc', loss='sparse_categorical_crossentropy')


In [16]:
h = model.fit(X_train, y_train, epochs=100, batch_size=10,
                validation_data = (validate_X_train, validate_y_train))

Epoch 1/100
12/12 [==============================] - 1s 15ms/step - loss: 1.0717 - acc: 0.3750 - val_loss: 1.0374 - val_acc: 0.6667
Epoch 2/100
12/12 [==============================] - 0s 4ms/step - loss: 1.0190 - acc: 0.6583 - val_loss: 0.9910 - val_acc: 0.7500
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9719 - acc: 0.6750 - val_loss: 0.9452 - val_acc: 0.7500
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9166 - acc: 0.6750 - val_loss: 0.8918 - val_acc: 0.7500
Epoch 5/100
12/12 [==============================] - 0s 3ms/step - loss: 0.8589 - acc: 0.8167 - val_loss: 0.8361 - val_acc: 0.8333
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 0.7987 - acc: 0.9083 - val_loss: 0.7765 - val_acc: 0.8333
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 0.7391 - acc: 0.8250 - val_loss: 0.7180 - val_acc: 0.8333
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 0.6821 - 

12/12 [==============================] - 0s 3ms/step - loss: 0.0687 - acc: 0.9667 - val_loss: 0.1120 - val_acc: 0.9167
Epoch 64/100
12/12 [==============================] - 0s 4ms/step - loss: 0.0683 - acc: 0.9750 - val_loss: 0.1226 - val_acc: 0.9167
Epoch 65/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0697 - acc: 0.9667 - val_loss: 0.1205 - val_acc: 0.9167
Epoch 66/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0652 - acc: 0.9750 - val_loss: 0.1193 - val_acc: 0.9167
Epoch 67/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0728 - acc: 0.9500 - val_loss: 0.1205 - val_acc: 0.9167
Epoch 68/100
12/12 [==============================] - 0s 4ms/step - loss: 0.0669 - acc: 0.9833 - val_loss: 0.1137 - val_acc: 0.9167
Epoch 69/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0664 - acc: 0.9750 - val_loss: 0.1216 - val_acc: 0.9583
Epoch 70/100
12/12 [==============================] - 0s 3ms/step - loss: 0.0625 - acc: 0

In [17]:
h.history

{'loss': [1.0717129707336426,
  1.0189800262451172,
  0.9718831181526184,
  0.9165647029876709,
  0.8589212894439697,
  0.7987315058708191,
  0.7390932440757751,
  0.6820542812347412,
  0.6243007779121399,
  0.5759695768356323,
  0.5300012230873108,
  0.49131864309310913,
  0.45606720447540283,
  0.42835357785224915,
  0.4003866910934448,
  0.3784198462963104,
  0.3546508252620697,
  0.3320811688899994,
  0.3094596266746521,
  0.29346513748168945,
  0.28269898891448975,
  0.2590669095516205,
  0.23796987533569336,
  0.22159042954444885,
  0.20809966325759888,
  0.19596901535987854,
  0.18278314173221588,
  0.17205862700939178,
  0.16528280079364777,
  0.16585169732570648,
  0.15332238376140594,
  0.14402011036872864,
  0.13293960690498352,
  0.1319592446088791,
  0.12828214466571808,
  0.12131770700216293,
  0.11567449569702148,
  0.11174700409173965,
  0.1103532686829567,
  0.10927252471446991,
  0.1004587709903717,
  0.09956289827823639,
  0.09749767184257507,
  0.10290162265300751,


In [18]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 17ms/step - loss: 0.1287 - acc: 0.9333


[0.12874624133110046, 0.9333333373069763]

In [19]:
pred = model.predict(X_test)
pred

1/1 [==============================] - 0s 64ms/step


array([[2.9070757e-04, 9.8761332e-01, 1.2095956e-02],
       [5.5001286e-04, 9.8384839e-01, 1.5601557e-02],
       [9.9789751e-01, 2.1024263e-03, 7.5841342e-09],
       [9.9884951e-01, 1.1505011e-03, 2.8028906e-09],
       [9.9981207e-01, 1.8793624e-04, 2.2778245e-10],
       [1.2444406e-04, 3.4045202e-01, 6.5942347e-01],
       [5.4847067e-07, 4.2343424e-03, 9.9576509e-01],
       [4.7182332e-04, 9.9502087e-01, 4.5072325e-03],
       [9.5252568e-01, 4.7473509e-02, 8.5119194e-07],
       [1.9095378e-04, 9.8764229e-01, 1.2166747e-02],
       [9.9878806e-01, 1.2119717e-03, 3.6287719e-09],
       [7.5907492e-06, 1.1874949e-02, 9.8811740e-01],
       [1.9898584e-05, 1.2863469e-01, 8.7134540e-01],
       [1.0869119e-03, 9.9851102e-01, 4.0204739e-04],
       [1.1824672e-07, 8.0410921e-04, 9.9919575e-01],
       [9.9863511e-01, 1.3648479e-03, 5.4786051e-09],
       [1.5074525e-04, 8.5819602e-01, 1.4165327e-01],
       [9.9833423e-01, 1.6657995e-03, 3.6989720e-09],
       [9.9983454e-01, 1.653

In [20]:
import numpy as np
np.set_printoptions(suppress=True)

pred= model.predict(X_test)
pred

1/1 [==============================] - 0s 15ms/step


array([[0.00029071, 0.9876133 , 0.01209596],
       [0.00055001, 0.9838484 , 0.01560156],
       [0.9978975 , 0.00210243, 0.00000001],
       [0.9988495 , 0.0011505 , 0.        ],
       [0.99981207, 0.00018794, 0.        ],
       [0.00012444, 0.34045202, 0.6594235 ],
       [0.00000055, 0.00423434, 0.9957651 ],
       [0.00047182, 0.99502087, 0.00450723],
       [0.9525257 , 0.04747351, 0.00000085],
       [0.00019095, 0.9876423 , 0.01216675],
       [0.99878806, 0.00121197, 0.        ],
       [0.00000759, 0.01187495, 0.9881174 ],
       [0.0000199 , 0.12863469, 0.8713454 ],
       [0.00108691, 0.998511  , 0.00040205],
       [0.00000012, 0.00080411, 0.99919575],
       [0.9986351 , 0.00136485, 0.00000001],
       [0.00015075, 0.858196  , 0.14165327],
       [0.9983342 , 0.0016658 , 0.        ],
       [0.99983454, 0.00016539, 0.        ],
       [0.00120826, 0.9912573 , 0.00753444],
       [0.00008846, 0.21656281, 0.7833488 ],
       [0.00013087, 0.98194826, 0.01792086],
       [0.

In [21]:
test_label = np.argmax( model.predict(X_test), axis=1)
test_label

1/1 [==============================] - 0s 28ms/step


array([1, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1,
       0, 0, 2, 2, 0, 1, 1, 2], dtype=int64)

In [22]:
y_test

63     1
53     1
1      0
9      0
22     0
127    2
112    2
55     1
41     0
86     1
26     0
121    2
116    2
81     1
120    2
3      0
133    2
31     0
46     0
59     1
149    2
52     1
35     0
23     0
100    2
110    2
8      0
129    2
71     1
105    2
Name: species_num, dtype: int64

In [23]:
np.mean(test_label ==y_test)

0.9333333333333333